### ISSUE TITLE
IAccessibleText links to dead page for text attribute specification

### ISSUE THREAD

**Issue by aleventhal** [LinuxA11y/IAccessible2#11]
IAccessibleText .textAttributes says:
```@param [out] textAttributes  
    A string of attributes describing the text.  The attributes are described in the
    <a href="http://www.linuxfoundation.org/en/Accessibility/IAccessible2/TextAttributes">
    text attributes specification</a> on the %IAccessible2 web site."
```
However that page does not exist.

By using the search field, I did find text attribute info here:
https://wiki.linuxfoundation.org/accessibility/iaccessible2/textattributes?s[]=text&s[]=attributes

However, who knows when that page will die. Shouldn't everything in the IA2 spec be moved over here? There are probably other problems like this. Future engineers (and me, currently), need access to the spec.

**Comment by Cccorrry** [comment]
Try open sources with https://nettyo

**Comment by michaelweghorn** [comment]
I've run into the same issue.

> By using the search field, I did find text attribute info here: [https://wiki.linuxfoundation.org/accessibility/iaccessible2/textattributes?s[]=text&s[]=attributes](https://wiki.linuxfoundation.org/accessibility/iaccessible2/textattributes?s%5B%5D=text&s%5B%5D=attributes)
> 
> However, who knows when that page will die. Shouldn't everything in the IA2 spec be moved over here? There are probably other problems like this. Future engineers (and me, currently), need access to the spec.

I can't say anything with regard to hosting the spec elsewhere, but I've at least submitted a pull request to update the doc to the working URL you mentioned: #23

**Comment by jcsteh** [comment]
I agree we should move everything here. We could use the GitHub wiki, but I think we should just move it into the repository so everything is in one place. It probably makes sense to convert it to Markdown or similar, though.

For now, I'm going to merge #23 so the URL is at least correct.
