### ISSUE TITLE
Need way to expose content insertions and deletions

### ISSUE THREAD

**Issue by aleventhal** [LinuxA11y/IAccessible2#4]
Content sometimes needs to indicate a content insertion/deletion (can be proposed change to content or has already occurred). In HTML this is indicated with the \<ins\> and \<del\> tags. Also, ARIA 1.2 plans to add roles for this. This will be very useful for online collaborative word processors and editors, such as Google Docs.

Mick Curran suggested that this be a text attribute. For example: diff:del and diff:ins. It could also be a role.

I suggest going with Mick's recommendation unless there's a counter proposal.

**Comment by jcsteh** [comment]
I agree with this being a text attribute. I'd suggest different naming, though; perhaps `revision:insertion`/`revision:deletion` or `change:insertion`/`change:deletion`. Note that we may eventually want supplementary attributes such as `revision-author` and `revision-date`.

@asurkov, thoughts?

**Comment by aleventhal** [comment]
I'm fine with revisition:insertion|deletion. Can we do that? We'll need to update the docs and file an issue for Firefox, right? I'll take care of asking Windows AT vendors to add support.

Here's the Chrome issue where I'm working on it: https://bugs.chromium.org/p/chromium/issues/detail?id=843744

**Comment by aleventhal** [comment]
Talked to @asurkov on IRC. We could also use IA2_ROLE_CONTENT_INSERTION and IA2_ROLE_CONTENT_DELETION with the following object attributes "cite" and "datetime". @jcsteh  what do you think?

**Comment by jcsteh** [comment]
[**@asurkov**](https://github.com/asurkov) commented on [May 23, 2018, 3:01 AM GMT+10](https://github.com/LinuxA11y/IAccessible2/issues/4#issuecomment-391066178 "2018-05-22T17:01:41Z - Replied by Github Reply Comments"):
> However these elements have @cite and @datetime attributes, which may be of interest of AT as well.

Ug. I forgot about these. Still, we could just expose their values as text attributes too if we went with text attributes.

> We have 5 years old bug (https://bugzilla.mozilla.org/show_bug.cgi?id=903187), where I mentioned, that Jamie twitted to go with object attributes, which means, to create accessible objects for elements.

Oh. I'm not quite sure why my past self decided that. I guess it was in response to needing to deal with the cite attribute.

> In short, I like text attributes conceptually, but it looks it is less flexible approach. At least, until we extend text attributes API to expose any value, like we did for object attributes.

I don't see a big issue with exposing cite and datetime as text attributes: revision-cite, revisoin-datetime. Am I missing something?

I'd like @MichaelDCurran's thoughts here. I know we discussed text attributes last time we spoke about this, but we didn't think about the cite attribute, which allows you to specify a URL describing the change. (That said, does anyone even use this?) However, it also occurred to me that we'll probably want to support quick nav to annotations and that might be a bit tricky for text attributes. Note that we'd have that same problem for spelling errors, though.

@Joanmarie, I'd also like your perspective on this regarding ATK, given that we generally try to keep IA2 and ATK in sync. In the past, [you've expressed a preference for objects over text attributes for sup/sub](https://bugzilla.mozilla.org/show_bug.cgi?id=1175640). Does this preference also apply to ins/del? Does ATK have roles for these already?

**Comment by aleventhal** [comment]
Spelling/grammar are already handled via invalid:spelling|grammar text attribute.
@jcsteh I didn't see you address the idea of using a role. This is what Mac does. We can use object attributes for cite and datetime.

**Comment by asurkov** [comment]
Seems Mac set a precedence, and thus it's easier to expose accessible objects for ins/del elements for all platforms. @aleventhal suggested to expose both, which may be reasonable, if the consensus is we want to expose those via text attributes on IA2/ATK. I'm not sure whether we need specialized roles for the elements in this case or we can go with generic ones.

**Comment by aleventhal** [comment]
@asurkov , I actually prefer just the new roles and no text attributes. I'll check with Mick. I consider the @cite and @datetime to be red herrings, but they could be exposed as object attributes.

**Comment by aleventhal** [comment]
Mick said he's ok with the roles. I tried to fork so that I could create a pull request, but I'm not permitted. Here is my suggested added text to AccessibleRoles.idl:

  /**
   * Content previously deleted or proposed to be deleted, e.g. in revision
   * history or a content view providing suggestions from reviewers.
   */
  IA2_ROLE_CONTENT_DELETION,

  /**
   * Content previously inserted or proposed to be inserted, e.g. in revision
   * history or a content view providing suggestions from reviewers.
   */
  IA2_ROLE_CONTENT_INSERTION

**Comment by asurkov** [comment]
We should fix it. Let me contact to the group owner.

**Comment by aleventhal** [comment]
Mick was fine with the roles in the end, because of consistency with HTML/ARIA/Mac. Can someone add something like this to the IDL? I tried to fork in order to do a pull req but didn't have permissions.

 /**
   * Content previously deleted or proposed to be deleted, e.g. in revision
   * history or a content view providing suggestions from reviewers.
   */
  IA2_ROLE_CONTENT_DELETION,

  /**
   * Content previously inserted or proposed to be inserted, e.g. in revision
   * history or a content view providing suggestions from reviewers.
   */
  IA2_ROLE_CONTENT_INSERTION

**Comment by asurkov** [comment]
@aleventhal I sent a request to allow forking and also created a pull request for your change https://github.com/LinuxA11y/IAccessible2/pull/5

**Comment by jcsteh** [comment]
#5 was merged and adds the roles. Closing.
